version: '3.9'

services:
  swagger:
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    ports:
    - 80:8080
    volumes:
    - ./doc:/usr/share/nginx/html/doc
    environment:
    - API_URL:doc/openapi.yaml

  