# Generated by Django 4.1 on 2022-08-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fcuser", "0004_alter_fcuser_useremail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="제목")),
                ("content", models.TextField(verbose_name="본문")),
                (
                    "registered_dtm",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록시간"),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fcuser.fcuser",
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "패스트캠퍼스 게시글",
                "verbose_name_plural": "패스트캠퍼스 게시글",
                "db_table": "fastcampus_board",
            },
        ),
    ]
