# Generated by Django 4.1 on 2022-08-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcuser", "0003_alter_fcuser_options_fcuser_useremail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcuser",
            name="useremail",
            field=models.EmailField(max_length=128, verbose_name="사용자이메일"),
        ),
    ]
